// Food items data with unique names
export const foodItems = [
  { id: "MAY-001", name: "Aloo Mutter Samosa", price: "₹20", image: "./css/images/food-items/Mayuri/aloo mutter samosa.png", quantity: 0 },
  { id: "MAY-002", name: "Aloo Tikki", price: "₹50", image: "./css/images/food-items/Mayuri/ALOO TIKKI.png", quantity: 0 },
  { id: "MAY-003", name: "Dahi bhalle", price: "₹60", image: "./css/images/food-items/Mayuri/dahi bhalla.png", quantity: 0 },
  { id: "MAY-004", name: "Dahi Puri", price: "₹60", image: "./css/images/food-items/Mayuri/dahi puri.png", quantity: 0 },
  { id: "MAY-005", name: "Indori Hot Dog", price: "₹60", image: "./css/images/food-items/Mayuri/indori hot dog.png", quantity: 0 },
  { id: "MAY-006", name: "Loaded Sandwhich", price: "₹80", image: "./css/images/food-items/Mayuri/LOADED SANDWITCH.jpg", quantity: 0 },
  { id: "MAY-007", name: "Masala Paneer Samosa", price: "₹30", image: "./css/images/food-items/Mayuri/masala paneer samosa.png", quantity: 0 },
  { id: "MAY-008", name: "Paneer Fried Momo", price: "₹120", image: "./css/images/food-items/Mayuri/paneer fried momo.jpg", quantity: 0 },
  { id: "MAY-009", name: "Paneer Hotdog", price: "₹80", image: "./css/images/food-items/Mayuri/paneer hotdog.jpg", quantity: 0 },
  { id: "MAY-010", name: "Paneer Steam Momo", price: "₹100", image: "./css/images/food-items/Mayuri/paneer steam momo.jpg", quantity: 0 },
  { id: "MAY-011", name: "Paneer Tikka", price: "₹120", image: "./css/images/food-items/Mayuri/paneer tikka.png", quantity: 0 },
  { id: "MAY-012", name: "Pani Puri", price: "₹40", image: "./css/images/food-items/Mayuri/pani puri.png", quantity: 0 },
  { id: "MAY-013", name: "Papdi Chat", price: "₹50", image: "./css/images/food-items/Mayuri/papdi chat.png", quantity: 0 },
  { id: "MAY-014", name: "Pav Bhaji", price: "₹80", image: "./css/images/food-items/Mayuri/pav bhaji.png", quantity: 0 },
  { id: "MAY-015", name: "Raj Kachori", price: "₹80", image: "./css/images/food-items/Mayuri/raj kachori.png", quantity: 0 },
  { id: "MAY-016", name: "Shahi Kachori", price: "₹30", image: "./css/images/food-items/Mayuri/shahi kachori.png", quantity: 0 },
  { id: "MAY-017", name: "Vada Pav", price: "₹50", image: "./css/images/food-items/Mayuri/vada pav.png", quantity: 0 },
  { id: "MAY-018", name: "Vada Sambhar", price: "₹50", image: "./css/images/food-items/Mayuri/vada sambhar.png", quantity: 0 },
  { id: "MAY-019", name: "Veg Burger", price: "₹60", image: "./css/images/food-items/Mayuri/veg burger.jpg", quantity: 0 },
  { id: "MAY-020", name: "Veg Cheese Burger", price: "₹80", image: "./css/images/food-items/Mayuri/veg cheese burger.jpg", quantity: 0 },
  { id: "MAY-021", name: "Veg Fried Momo", price: "₹100", image: "./css/images/food-items/Mayuri/veg fried momo.jpg", quantity: 0 },
  { id: "MAY-022", name: "Veg Steam Momo", price: "₹80", image: "./css/images/food-items/Mayuri/veg steam momo.jpg", quantity: 0 },
  { id: "MAY-023", name: "Blueberry Soda", price: "₹80", image: "./css/images/food-items/Mayuri/blue berry soda.jpg", quantity: 0 },
  { id: "MAY-024", name: "Cold Coffee", price: "₹80", image: "./css/images/food-items/Mayuri/cold coffee.jpg", quantity: 0 },
  { id: "MAY-025", name: "Green Apple Soda", price: "₹80", image: "./css/images/food-items/Mayuri/green apple soda.jpg", quantity: 0 },
  { id: "MAY-026", name: "Mint Mojito", price: "₹80", image: "./css/images/food-items/Mayuri/mint mojito.jpg", quantity: 0 },
  { id: "MAY-027", name: "Kiwi Punch", price: "₹80", image: "./css/images/food-items/Mayuri/kiwi punch.jpg", quantity: 0 },
  { id: "MAY-028", name: "Pineapple Soda", price: "₹80", image: "./css/images/food-items/Mayuri/pineapple juice.jpg", quantity: 0 },
  { id: "MAY-029", name: "Watermelon Mojito", price: "₹100", image: "./css/images/food-items/Mayuri/watermelon mojito.jpg", quantity: 0 },
  { id: "MAY-030", name: "Strawberry Shake", price: "₹80", image: "./css/images/food-items/Mayuri/Strawberry Shake.jpg", quantity: 0 },
  { id: "MAY-031", name: "Banana Shake", price: "₹80", image: "./css/images/food-items/Mayuri/banana shake.jpg", quantity: 0 },
  { id: "MAY-032", name: "Mango Shake", price: "₹100", image: "./css/images/food-items/Mayuri/mango shake.jpg", quantity: 0 },
  { id: "MAY-033", name: "Lassi", price: "₹60", image: "./css/images/food-items/Mayuri/Lassi.png", quantity: 0 },
  { id: "MAY-034", name: "Mango Lassi", price: "₹80", image: "./css/images/food-items/Mayuri/Mango Lassi.png", quantity: 0 },
  { id: "MAY-035", name: "Chocolate Lassi", price: "₹80", image: "./css/images/food-items/Mayuri/Chocolate Lassi.png", quantity: 0 },
  { id: "MAY-036", name: "Mini Idli", price: "₹50", image: "./css/images/food-items/Mayuri/mini idli.png", quantity: 0 },
  { id: "MAY-037", name: "Fried Idli", price: "₹50", image: "./css/images/food-items/Mayuri/fried idli.png", quantity: 0 },
  { id: "MAY-038", name: "Dosa Plain", price: "₹80", image: "./css/images/food-items/Mayuri/dosa plain.png", quantity: 0 },
  { id: "MAY-039", name: "Masala Dosa", price: "₹219", image: "./css/images/food-items/Mayuri/masala dosa.jpg", quantity: 0 },
  { id: "MAY-040", name: "Jinni Dosa", price: "₹110", image: "./css/images/food-items/Mayuri/jinni dosa.png", quantity: 0 },
  { id: "MAY-041", name: "Corn Cheese Dosa", price: "₹110", image: "./css/images/food-items/Mayuri/corn cheese dosa.png", quantity: 0 },
  { id: "MAY-042", name: "Paneer Masala Dosa", price: "₹110", image: "./css/images/food-items/Mayuri/paneer masala dosa.png", quantity: 0 },
  { id: "MAY-043", name: "Rasmalai", price: "₹30", image: "./css/images/food-items/Mayuri/rasmalai.png", quantity: 0 },
  { id: "MAY-044", name: "Gulab Jamun", price: "₹20", image: "./css/images/food-items/Mayuri/gulab jamun.png", quantity: 0 },
  { id: "MAY-045", name: "Rabdi", price: "₹50", image: "./css/images/food-items/Mayuri/rabdi.png", quantity: 0 },
  { id: "MAY-046", name: "Mango Rabdi", price: "₹60", image: "./css/images/food-items/Mayuri/mango rabdi.png", quantity: 0 }
];