// Food items data with unique names
export const foodItems = [
  { name: "Sweet Corn Pizza", price: "₹200", image: "./css/images/food-items/Underbelly/sweet corn pizza.jpg", quantity: 0 },
  { name: "Sweet Corn Pizza", price: "₹200", image: "./css/images/food-items/Underbelly/sweet corn pizza.jpg", quantity: 0 },
  { name: "UB Special Veg Pizza", price: "₹200", image: "./css/images/food-items/Underbelly/UB speacial veg pizza.jpg", quantity: 0 },
  { name: "Paneer Tikka Pizza", price: "₹200", image: "./css/images/food-items/Underbelly/paneer pizza.png", quantity: 0 },
  { name: "Classic Margherita Pizza", price: "₹200", image: "./css/images/food-items/Underbelly/MARGHERITA PIZZA.jpg", quantity: 0 },
  { name: "UB Special Non Veg Pizza", price: "₹230", image: "./css/images/food-items/Underbelly/ub special non veg pizza.jpg", quantity: 0 },
  { name: "Chicken Tikka Pizza", price: "₹230", image: "./css/images/food-items/Underbelly/chicken tikka pizza.jpg", quantity: 0 },
  { name: "Chicken Tikka Pizza", price: "₹230", image: "./css/images/food-items/Underbelly/chicken tikka pizza.jpg", quantity: 0 },
  { name: "Penne Alfredo Pasta", price: "₹110", image: "./css/images/food-items/Underbelly/penne alfredo pasta.jpg", quantity: 0 },
  { name: "Penne Arrabiata Pasta", price: "₹110", image: "./css/images/food-items/Underbelly/penne arrabiata pasta.jpg", quantity: 0 },
  { name: "Pink Sauce Pasta", price: "₹110", image: "./css/images/food-items/Underbelly/pink sauce pasta.jpg", quantity: 0 },
  { name: "Penne Alfredo Chicken Pasta", price: "₹130", image: "./css/images/food-items/Underbelly/penne alfredo chicken pasta.jpg", quantity: 0 },
  { name: "Pink Chicken Sauce Pasta", price: "₹130", image: "./css/images/food-items/Underbelly/pink chicken sauce pasta.jpg", quantity: 0 },
  { name: "Penne Arrabiata Chicken Pasta", price: "₹130", image: "./css/images/food-items/Underbelly/penne arrabiata chicken pasta.jpg", quantity: 0 },
  { name: "Penne Arrabiata Chicken Pasta", price: "₹130", image: "./css/images/food-items/Underbelly/penne arrabiata chicken pasta.jpg", quantity: 0 },
  { name: "Veg Momo", price: "₹110", image: "./css/images/food-items/Underbelly/veg momo.jpg", quantity: 0 },
  { name: "Paneer Momo", price: "₹130", image: "./css/images/food-items/Underbelly/paneer momo.jpg", quantity: 0 },
  { name: "Chicken Momo", price: "₹140", image: "./css/images/food-items/Underbelly/chicken momo.jpg", quantity: 0 },
  { name: "Bread Omelette", price: "₹67", image: "./css/images/food-items/Underbelly/bread omlette.jpg", quantity: 0 },
  { name: "Masala Omelette", price: "₹37", image: "./css/images/food-items/Underbelly/masala omelette.jpg", quantity: 0 },
  { name: "Egg Burji", price: "₹37", image: "./css/images/food-items/Underbelly/egg bhurji.png", quantity: 0 },
  { name: "Chicken Nuggets", price: "₹152", image: "./css/images/food-items/Underbelly/chicken nuggets.jpg", quantity: 0 },
  { name: "Chicken Wings", price: "₹152", image: "./css/images/food-items/Underbelly/chicken wings.jpg", quantity: 0 },
  { name: "Chicken Tikka", price: "₹168", image: "./css/images/food-items/Underbelly/chicken tikka.jpg", quantity: 0 },
  { name: "Chicken Malai Tikka", price: "₹168", image: "./css/images/food-items/Underbelly/CHICKEN malai tikka.png", quantity: 0 },
  { name: "Tandoori Chicken Half", price: "₹210", image: "./css/images/food-items/Underbelly/tandoori CHICKEN.jpg", quantity: 0 },
  { name: "Tandoori Chicken Full", price: "₹399", image: "./css/images/food-items/Underbelly/tandoori chicken full.jpg", quantity: 0 },
  { name: "Chili Chicken Gravy", price: "₹150", image: "./css/images/food-items/Underbelly/chilly chicken gravy.jpg", quantity: 0 },
  { name: "Dragon Chicken", price: "₹152", image: "./css/images/food-items/Underbelly/dragon chicken.jpg", quantity: 0 },
  { name: "Classic French Fries", price: "₹95", image: "./css/images/food-items/Underbelly/classic french fries.jpg", quantity: 0 },
  { name: "Masala French Fries", price: "₹105", image: "./css/images/food-items/Underbelly/masala french fries.jpg", quantity: 0 },
  { name: "Paneer Tikka", price: "₹158", image: "./css/images/food-items/Underbelly/paneer tikka.png", quantity: 0 }
];
