// Food items data with unique names
export const foodItems = [
  { name: "Sweet Corn Pizza", price: "₹200", image: "./css/images/food-items/Underbelly/sweet corn pizza.jpg", quantity: 0 },
  { name: "Sweet Corn Pizza", price: "₹200", image: "./css/images/food-items/Underbelly/sweet corn pizza.jpg", quantity: 0 },
  { name: "UB Special Veg Pizza", price: "₹200", image: "./css/images/food-items/Underbelly/UB speacial veg pizza.jpg", quantity: 0 },
  { name: "Paneer Tikka Pizza", price: "₹200", image: "./css/images/food-items/Underbelly/paneer pizza.png", quantity: 0 },
  { name: "Classic Margherita Pizza", price: "₹200", image: "./css/images/food-items/Underbelly/MARGHERITA PIZZA.jpg", quantity: 0 },
  { name: "UB Special Non Veg Pizza", price: "₹230", image: "./css/images/food-items/Underbelly/ub special non veg pizza.jpg", quantity: 0 },
  { name: "Chicken Tikka Pizza", price: "₹230", image: "./css/images/food-items/Underbelly/chicken tikka pizza.jpg", quantity: 0 },
  { name: "Chicken Tikka Pizza", price: "₹230", image: "./css/images/food-items/Underbelly/chicken tikka pizza.jpg", quantity: 0 },
  { name: "Penne Alfredo Pasta", price: "₹110", image: "./css/images/food-items/Underbelly/penne alfredo pasta.jpg", quantity: 0 },
  { name: "Penne Arrabiata Pasta", price: "₹110", image: "./css/images/food-items/Underbelly/penne arrabiata pasta.jpg", quantity: 0 },
  { name: "Pink Sauce Pasta", price: "₹110", image: "./css/images/food-items/Underbelly/pink sauce pasta.jpg", quantity: 0 },
  { name: "Penne Alfredo Chicken Pasta", price: "₹130", image: "./css/images/food-items/Underbelly/penne alfredo chicken pasta.jpg", quantity: 0 },
  { name: "Pink Chicken Sauce Pasta", price: "₹130", image: "./css/images/food-items/Underbelly/pink chicken sauce pasta.jpg", quantity: 0 },
  { name: "Penne Arrabiata Chicken Pasta", price: "₹130", image: "./css/images/food-items/Underbelly/penne arrabiata chicken pasta.jpg", quantity: 0 },
  { name: "Penne Arrabiata Chicken Pasta", price: "₹130", image: "./css/images/food-items/Underbelly/penne arrabiata chicken pasta.jpg", quantity: 0 },
  { name: "Veg Momo", price: "₹110", image: "./css/images/food-items/Underbelly/veg momo.jpg", quantity: 0 },
  { name: "Paneer Momo", price: "₹130", image: "./css/images/food-items/Underbelly/paneer momo.jpg", quantity: 0 },
  { name: "Chicken Momo", price: "₹140", image: "./css/images/food-items/Underbelly/chicken momo.jpg", quantity: 0 },
  { name: "Bread Omelette", price: "₹67", image: "./css/images/food-items/Underbelly/bread omlette.jpg", quantity: 0 },
  { name: "Masala Omelette", price: "₹37", image: "./css/images/food-items/Underbelly/masala omelette.jpg", quantity: 0 },
  { name: "Egg Burji", price: "₹37", image: "./css/images/food-items/Underbelly/egg bhurji.png", quantity: 0 },
  { name: "Chicken Nuggets", price: "₹152", image: "./css/images/food-items/Underbelly/chicken nuggets.jpg", quantity: 0 },
  { name: "Chicken Wings", price: "₹152", image: "./css/images/food-items/Underbelly/chicken wings.jpg", quantity: 0 },
  { name: "Chicken Tikka", price: "₹168", image: "./css/images/food-items/Underbelly/chicken tikka.jpg", quantity: 0 },
  { name: "Chicken Malai Tikka", price: "₹168", image: "./css/images/food-items/Underbelly/CHICKEN malai tikka.png", quantity: 0 },
  { name: "Tandoori Chicken Half", price: "₹210", image: "./css/images/food-items/Underbelly/tandoori CHICKEN.jpg", quantity: 0 },
  { name: "Tandoori Chicken Full", price: "₹399", image: "./css/images/food-items/Underbelly/tandoori chicken full.jpg", quantity: 0 },
  { name: "Chili Chicken Gravy", price: "₹150", image: "./css/images/food-items/Underbelly/chilly chicken gravy.jpg", quantity: 0 },
  { name: "Dragon Chicken", price: "₹152", image: "./css/images/food-items/Underbelly/dragon chicken.jpg", quantity: 0 },
  { name: "Classic French Fries", price: "₹95", image: "./css/images/food-items/Underbelly/classic french fries.jpg", quantity: 0 },
  { name: "Masala French Fries", price: "₹105", image: "./css/images/food-items/Underbelly/masala french fries.jpg", quantity: 0 },
  { name: "Paneer Tikka", price: "₹158", image: "./css/images/food-items/Underbelly/paneer tikka.png", quantity: 0 },
  { name: "Paneer Malai Tikka", price: "₹158", image: "./css/images/food-items/Underbelly/paneer malai tikka.png", quantity: 0 },
  { name: "Chilly Paneer Dry", price: "₹130", image: "./css/images/food-items/Underbelly/chilly paneer dry.png", quantity: 0 },
  { name: "Veg Manchurian", price: "₹137", image: "./css/images/food-items/Underbelly/veg manchurian.png", quantity: 0 },
  { name: "Double Cheese Sandwich", price: "₹89", image: "./css/images/food-items/Underbelly/double cheese sandwich.png", quantity: 0 },
  { name: "Sweet Corn Sandwich", price: "₹89", image: "./css/images/food-items/Underbelly/sweet corn sandwitch.jpg", quantity: 0 },
  { name: "Paneer Tikka Sandwich", price: "₹100", image: "./css/images/food-items/Underbelly/paneer tikka sandwich.png", quantity: 0 },
  { name: "Chicken Tikka Sandwich", price: "₹121", image: "./css/images/food-items/Underbelly/chicken tikka sandwich.jpg", quantity: 0 },
  { name: "Veg Cheese Burger", price: "₹95", image: "./css/images/food-items/Underbelly/veg cheese burger.jpg", quantity: 0 },
  { name: "Chicken Burger", price: "₹116", image: "./css/images/food-items/Underbelly/chicken burger.jpg", quantity: 0 },
  { name: "Veg Wrap", price: "₹95", image: "./css/images/food-items/Underbelly/veg wrap.jpg", quantity: 0 },
  { name: "Paneer Wrap", price: "₹100", image: "./css/images/food-items/Underbelly/paneer wrap.jpg", quantity: 0 },
  { name: "Chicken Wrap", price: "₹121", image: "./css/images/food-items/Underbelly/chicken wrap.jpg", quantity: 0 },
  { name: "Tandoori Soya Chaap", price: "₹150", image: "./css/images/food-items/Underbelly/tandoori soya chaap.png", quantity: 0 },
  { name: "Malai Soya Chaap", price: "₹150", image: "./css/images/food-items/Underbelly/malai soya chaap.png", quantity: 0 },
  { name: "Veg Noodles", price: "₹130", image: "./css/images/food-items/Underbelly/veg noodles.jpg", quantity: 0 },
  { name: "Schezwan Veg Noodles", price: "₹131", image: "./css/images/food-items/Underbelly/schezwan veg noodles.png", quantity: 0 },
  { name: "Chicken Noodles", price: "₹142", image: "./css/images/food-items/Underbelly/chicken noodles.png", quantity: 0 },
  { name: "Schezwan Chicken Noodles", price: "₹152", image: "./css/images/food-items/Underbelly/schezwan chicken noodles.png", quantity: 0 },
  { name: "Egg Fried Rice", price: "₹142", image: "./css/images/food-items/Underbelly/egg fried rice.png", quantity: 0 },
  { name: "Schezwan Veg Fried Rice", price: "₹131", image: "./css/images/food-items/Underbelly/schezwan veg fried rice.png", quantity: 0 },
  { name: "Schezwan Chicken Fried Rice", price: "₹152", image: "./css/images/food-items/Underbelly/schezwan chicken fried rice.png", quantity: 0 },
  { name: "Plain Dosa", price: "₹70", image: "./css/images/food-items/Underbelly/dosa plain.png", quantity: 0 },
  { name: "Masala Dosa", price: "₹80", image: "./css/images/food-items/Underbelly/masala dosa.png", quantity: 0 },
  { name: "Paneer Kheema Dosa", price: "₹105", image: "./css/images/food-items/Underbelly/paneer kheema dosa.png", quantity: 0 },
  { name: "Paneer Butter Masala", price: "₹158", image: "./css/images/food-items/Underbelly/paneer butter masala.png", quantity: 0 },
  { name: "Kadai Paneer Masala", price: "₹147", image: "./css/images/food-items/Underbelly/kadai paneer masala.png", quantity: 0 },
  { name: "Paneer Tikka Masala", price: "₹158", image: "./css/images/food-items/Underbelly/paneer tikka masala.png", quantity: 0 },
  { name: "Shahi Paneer", price: "₹147", image: "./css/images/food-items/Underbelly/shahi paneer.png", quantity: 0 },
  { name: "Chicken Tikka Masala", price: "₹168", image: "./css/images/food-items/Underbelly/chicken tikka masala.png", quantity: 0 },
  { name: "Schezwan Chicken Gravy", price: "₹168", image: "./css/images/food-items/Underbelly/schezwan chicken gravy.png", quantity: 0 },
  { name: "Dal Makhni", price: "₹150", image: "./css/images/food-items/Underbelly/dal makhni.png", quantity: 0 },
  { name: "Kadai Sabzi", price: "₹140", image: "./css/images/food-items/Underbelly/kadai sabzi.png", quantity: 0 },
  { name: "Punjabi Chicken Masala", price: "₹168", image: "./css/images/food-items/Underbelly/punjabi chicken masala.png", quantity: 0 },
  { name: "Butter Chicken Masala", price: "₹168", image: "./css/images/food-items/Underbelly/butter chicken masala.png", quantity: 0 },
  { name: "Chicken Lababdar", price: "₹168", image: "./css/images/food-items/Underbelly/chicken lababdar.png", quantity: 0 },
  { name: "Tandoori Roti", price: "₹30", image: "./css/images/food-items/Underbelly/tandoori roti.png", quantity: 0 },
  { name: "Paneer Kulcha (2 Pcs)", price: "₹130", image: "./css/images/food-items/Underbelly/paneer kulcha.png", quantity: 0 },
  { name: "Tandoori Aloo Paratha (2 Pcs)", price: "₹100", image: "./css/images/food-items/Underbelly/tandoori aloo paratha.png", quantity: 0 },
  { name: "Butter Naan", price: "₹42", image: "./css/images/food-items/Underbelly/butter naan.png", quantity: 0 },
  { name: "Garlic Naan", price: "₹45", image: "./css/images/food-items/Underbelly/garlic naan.png", quantity: 0 },
  { name: "Ginger Tea", price: "₹15", image: "./css/images/food-items/Underbelly/ginger tea.jpg", quantity: 0 },
  { name: "Coffee", price: "₹15", image: "./css/images/food-items/Underbelly/coffee.jpg", quantity: 0 }
];
