// Food items data with unique names
export const foodItems = [
  {
    id: 'UB-001',
    name: 'Sweet Corn Pizza',
    price: '₹200',
    image: './css/images/food-items/Underbelly/sweet corn pizza.jpg',
    quantity: 0,
  },
  {
    id: 'UB-002',
    name: 'Sweet Corn Pizza',
    price: '₹200',
    image: './css/images/food-items/Underbelly/sweet corn pizza.jpg',
    quantity: 0,
  },
  {
    id: 'UB-003',
    name: 'UB Special Veg Pizza',
    price: '₹200',
    image: './css/images/food-items/Underbelly/UB speacial veg pizza.jpg',
    quantity: 0,
  },
  {
    id: 'UB-004',
    name: 'Paneer Tikka Pizza',
    price: '₹200',
    image: './css/images/food-items/Underbelly/paneer pizza.png',
    quantity: 0,
  },
  {
    id: 'UB-005',
    name: 'Classic Margherita Pizza',
    price: '₹200',
    image: './css/images/food-items/Underbelly/MARGHERITA PIZZA.jpg',
    quantity: 0,
  },
  {
    id: 'UB-006',
    name: 'UB Special Non Veg Pizza',
    price: '₹230',
    image: './css/images/food-items/Underbelly/ub special non veg pizza.jpg',
    quantity: 0,
  },
  {
    id: 'UB-007',
    name: 'Chicken Tikka Pizza',
    price: '₹230',
    image: './css/images/food-items/Underbelly/chicken tikka pizza.jpg',
    quantity: 0,
  },
  {
    id: 'UB-008',
    name: 'Chicken Tikka Pizza',
    price: '₹230',
    image: './css/images/food-items/Underbelly/chicken tikka pizza.jpg',
    quantity: 0,
  },
  {
    id: 'UB-009',
    name: 'Penne Alfredo Pasta',
    price: '₹110',
    image: './css/images/food-items/Underbelly/penne alfredo pasta.jpg',
    quantity: 0,
  },
  {
    id: 'UB-010',
    name: 'Penne Arrabiata Pasta',
    price: '₹110',
    image: './css/images/food-items/Underbelly/penne arrabiata pasta.jpg',
    quantity: 0,
  },
  {
    id: 'UB-011',
    name: 'Pink Sauce Pasta',
    price: '₹110',
    image: './css/images/food-items/Underbelly/pink sauce pasta.jpg',
    quantity: 0,
  },
  {
    id: 'UB-012',
    name: 'Penne Alfredo Chicken Pasta',
    price: '₹130',
    image: './css/images/food-items/Underbelly/penne alfredo chicken pasta.jpg',
    quantity: 0,
  },
  {
    id: 'UB-013',
    name: 'Pink Chicken Sauce Pasta',
    price: '₹130',
    image: './css/images/food-items/Underbelly/pink chicken sauce pasta.jpg',
    quantity: 0,
  },
  {
    id: 'UB-014',
    name: 'Penne Arrabiata Chicken Pasta',
    price: '₹130',
    image: './css/images/food-items/Underbelly/penne arrabiata chicken pasta.jpg',
    quantity: 0,
  },
  {
    id: 'UB-015',
    name: 'Penne Arrabiata Chicken Pasta',
    price: '₹130',
    image: './css/images/food-items/Underbelly/penne arrabiata chicken pasta.jpg',
    quantity: 0,
  },
  {
    id: 'UB-016',
    name: 'Veg Momo',
    price: '₹110',
    image: './css/images/food-items/Underbelly/veg momo.jpg',
    quantity: 0,
  },
  {
    id: 'UB-017',
    name: 'Paneer Momo',
    price: '₹130',
    image: './css/images/food-items/Underbelly/paneer momo.jpg',
    quantity: 0,
  },
  {
    id: 'UB-018',
    name: 'Chicken Momo',
    price: '₹140',
    image: './css/images/food-items/Underbelly/chicken momo.jpg',
    quantity: 0,
  },
  {
    id: 'UB-019',
    name: 'Bread Omelette',
    price: '₹67',
    image: './css/images/food-items/Underbelly/bread omlette.jpg',
    quantity: 0,
  },
  {
    id: 'UB-020',
    name: 'Masala Omelette',
    price: '₹37',
    image: './css/images/food-items/Underbelly/masala omelette.jpg',
    quantity: 0,
  },
  {
    id: 'UB-021',
    name: 'Egg Burji',
    price: '₹37',
    image: './css/images/food-items/Underbelly/egg bhurji.png',
    quantity: 0,
  },
  {
    id: 'UB-022',
    name: 'Chicken Nuggets',
    price: '₹152',
    image: './css/images/food-items/Underbelly/chicken nuggets.jpg',
    quantity: 0,
  },
  {
    id: 'UB-023',
    name: 'Chicken Wings',
    price: '₹152',
    image: './css/images/food-items/Underbelly/chicken wings.jpg',
    quantity: 0,
  },
  {
    id: 'UB-024',
    name: 'Chicken Tikka',
    price: '₹168',
    image: './css/images/food-items/Underbelly/chicken tikka.jpg',
    quantity: 0,
  },
  {
    id: 'UB-025',
    name: 'Chicken Malai Tikka',
    price: '₹168',
    image: './css/images/food-items/Underbelly/CHICKEN malai tikka.png',
    quantity: 0,
  },
  {
    id: 'UB-026',
    name: 'Tandoori Chicken Half',
    price: '₹210',
    image: './css/images/food-items/Underbelly/tandoori CHICKEN.jpg',
    quantity: 0,
  },
  {
    id: 'UB-027',
    name: 'Tandoori Chicken Full',
    price: '₹399',
    image: './css/images/food-items/Underbelly/tandoori chicken full.jpg',
    quantity: 0,
  },
  {
    id: 'UB-028',
    name: 'Chili Chicken Gravy',
    price: '₹150',
    image: './css/images/food-items/Underbelly/chilly chicken gravy.jpg',
    quantity: 0,
  },
  {
    id: 'UB-029',
    name: 'Dragon Chicken',
    price: '₹152',
    image: './css/images/food-items/Underbelly/dragon chicken.jpg',
    quantity: 0,
  },
  {
    id: 'UB-030',
    name: 'Classic French Fries',
    price: '₹95',
    image: './css/images/food-items/Underbelly/classic french fries.jpg',
    quantity: 0,
  },
  {
    id: 'UB-031',
    name: 'Masala French Fries',
    price: '₹105',
    image: './css/images/food-items/Underbelly/masala french fries.jpg',
    quantity: 0,
  },
  {
    id: 'UB-032',
    name: 'Paneer Tikka',
    price: '₹158',
    image: './css/images/food-items/Underbelly/paneer tikka.png',
    quantity: 0,
  },
  {
    id: 'UB-033',
    name: 'Paneer Malai Tikka',
    price: '₹158',
    image: './css/images/food-items/Underbelly/paneer malai tikka.png',
    quantity: 0,
  },
  {
    id: 'UB-034',
    name: 'Chilly Paneer Dry',
    price: '₹130',
    image: './css/images/food-items/Underbelly/chilly paneer dry.png',
    quantity: 0,
  },
  {
    id: 'UB-035',
    name: 'Veg Manchurian',
    price: '₹137',
    image: './css/images/food-items/Underbelly/veg manchurian.png',
    quantity: 0,
  },
  {
    id: 'UB-036',
    name: 'Double Cheese Sandwich',
    price: '₹89',
    image: './css/images/food-items/Underbelly/double cheese sandwich.png',
    quantity: 0,
  },
  {
    id: 'UB-037',
    name: 'Sweet Corn Sandwich',
    price: '₹89',
    image: './css/images/food-items/Underbelly/sweet corn sandwitch.jpg',
    quantity: 0,
  },
  {
    id: 'UB-038',
    name: 'Paneer Tikka Sandwich',
    price: '₹100',
    image: './css/images/food-items/Underbelly/paneer tikka sandwich.png',
    quantity: 0,
  },
  {
    id: 'UB-039',
    name: 'Chicken Tikka Sandwich',
    price: '₹121',
    image: './css/images/food-items/Underbelly/chicken tikka sandwich.jpg',
    quantity: 0,
  },
  {
    id: 'UB-040',
    name: 'Veg Cheese Burger',
    price: '₹95',
    image: './css/images/food-items/Underbelly/veg cheese burger.jpg',
    quantity: 0,
  },
  {
    id: 'UB-041',
    name: 'Chicken Burger',
    price: '₹116',
    image: './css/images/food-items/Underbelly/chicken burger.jpg',
    quantity: 0,
  },
  {
    id: 'UB-042',
    name: 'Veg Wrap',
    price: '₹95',
    image: './css/images/food-items/Underbelly/veg wrap.jpg',
    quantity: 0,
  },
  {
    id: 'UB-043',
    name: 'Paneer Wrap',
    price: '₹100',
    image: './css/images/food-items/Underbelly/paneer wrap.jpg',
    quantity: 0,
  },
  {
    id: 'UB-044',
    name: 'Chicken Wrap',
    price: '₹121',
    image: './css/images/food-items/Underbelly/chicken wrap.jpg',
    quantity: 0,
  },
  {
    id: 'UB-045',
    name: 'Tandoori Soya Chaap',
    price: '₹150',
    image: './css/images/food-items/Underbelly/tandoori soya chaap.png',
    quantity: 0,
  },
  {
    id: 'UB-046',
    name: 'Malai Soya Chaap',
    price: '₹150',
    image: './css/images/food-items/Underbelly/malai soya chaap.png',
    quantity: 0,
  },
  {
    id: 'UB-047',
    name: 'Veg Noodles',
    price: '₹130',
    image: './css/images/food-items/Underbelly/veg noodles.jpg',
    quantity: 0,
  },
  {
    id: 'UB-048',
    name: 'Schezwan Veg Noodles',
    price: '₹131',
    image: './css/images/food-items/Underbelly/schezwan veg noodles.png',
    quantity: 0,
  },
  {
    id: 'UB-049',
    name: 'Chicken Noodles',
    price: '₹142',
    image: './css/images/food-items/Underbelly/chicken noodles.png',
    quantity: 0,
  },
  {
    id: 'UB-050',
    name: 'Schezwan Chicken Noodles',
    price: '₹152',
    image: './css/images/food-items/Underbelly/schezwan chicken noodles.png',
    quantity: 0,
  },
  {
    id: 'UB-051',
    name: 'Egg Fried Rice',
    price: '₹142',
    image: './css/images/food-items/Underbelly/egg fried rice.png',
    quantity: 0,
  },
  {
    id: 'UB-052',
    name: 'Schezwan Veg Fried Rice',
    price: '₹131',
    image: './css/images/food-items/Underbelly/schezwan veg fried rice.png',
    quantity: 0,
  },
  {
    id: 'UB-053',
    name: 'Schezwan Chicken Fried Rice',
    price: '₹152',
    image: './css/images/food-items/Underbelly/schezwan chicken fried rice.png',
    quantity: 0,
  },
  {
    id: 'UB-054',
    name: 'Plain Dosa',
    price: '₹70',
    image: './css/images/food-items/Underbelly/dosa plain.png',
    quantity: 0,
  },
  {
    id: 'UB-055',
    name: 'Masala Dosa',
    price: '₹80',
    image: './css/images/food-items/Underbelly/masala dosa.png',
    quantity: 0,
  },
  {
    id: 'UB-056',
    name: 'Paneer Kheema Dosa',
    price: '₹105',
    image: './css/images/food-items/Underbelly/paneer kheema dosa.png',
    quantity: 0,
  },
  {
    id: 'UB-057',
    name: 'Paneer Butter Masala',
    price: '₹158',
    image: './css/images/food-items/Underbelly/paneer butter masala.png',
    quantity: 0,
  },
  {
    id: 'UB-058',
    name: 'Kadai Paneer Masala',
    price: '₹147',
    image: './css/images/food-items/Underbelly/kadai paneer masala.png',
    quantity: 0,
  },
  {
    id: 'UB-059',
    name: 'Paneer Tikka Masala',
    price: '₹158',
    image: './css/images/food-items/Underbelly/paneer tikka masala.png',
    quantity: 0,
  },
  {
    id: 'UB-060',
    name: 'Shahi Paneer',
    price: '₹147',
    image: './css/images/food-items/Underbelly/shahi paneer.png',
    quantity: 0,
  },
  {
    id: 'UB-061',
    name: 'Chicken Tikka Masala',
    price: '₹168',
    image: './css/images/food-items/Underbelly/chicken tikka masala.png',
    quantity: 0,
  },
  {
    id: 'UB-062',
    name: 'Schezwan Chicken Gravy',
    price: '₹168',
    image: './css/images/food-items/Underbelly/schezwan chicken gravy.png',
    quantity: 0,
  },
  {
    id: 'UB-063',
    name: 'Dal Makhni',
    price: '₹150',
    image: './css/images/food-items/Underbelly/dal makhni.png',
    quantity: 0,
  },
  {
    id: 'UB-064',
    name: 'Kadai Sabzi',
    price: '₹140',
    image: './css/images/food-items/Underbelly/kadai sabzi.png',
    quantity: 0,
  },
  {
    id: 'UB-065',
    name: 'Punjabi Chicken Masala',
    price: '₹168',
    image: './css/images/food-items/Underbelly/punjabi chicken masala.png',
    quantity: 0,
  },
  {
    id: 'UB-066',
    name: 'Butter Chicken Masala',
    price: '₹168',
    image: './css/images/food-items/Underbelly/butter chicken masala.png',
    quantity: 0,
  },
  {
    id: 'UB-067',
    name: 'Chicken Lababdar',
    price: '₹168',
    image: './css/images/food-items/Underbelly/chicken lababdar.png',
    quantity: 0,
  },
  {
    id: 'UB-068',
    name: 'Tandoori Roti',
    price: '₹30',
    image: './css/images/food-items/Underbelly/tandoori roti.png',
    quantity: 0,
  },
  {
    id: 'UB-069',
    name: 'Paneer Kulcha (2 Pcs)',
    price: '₹130',
    image: './css/images/food-items/Underbelly/paneer kulcha.png',
    quantity: 0,
  },
  {
    id: 'UB-070',
    name: 'Tandoori Aloo Paratha (2 Pcs)',
    price: '₹100',
    image: './css/images/food-items/Underbelly/tandoori aloo paratha.png',
    quantity: 0,
  },
  {
    id: 'UB-071',
    name: 'Butter Naan',
    price: '₹42',
    image: './css/images/food-items/Underbelly/butter naan.png',
    quantity: 0,
  },
  {
    id: 'UB-072',
    name: 'Garlic Naan',
    price: '₹45',
    image: './css/images/food-items/Underbelly/garlic naan.png',
    quantity: 0,
  },
  {
    id: 'UB-073',
    name: 'Ginger Tea',
    price: '₹15',
    image: './css/images/food-items/Underbelly/ginger tea.jpg',
    quantity: 0,
  },
  {
    id: 'UB-074',
    name: 'Coffee',
    price: '₹15',
    image: './css/images/food-items/Underbelly/coffee.jpg',
    quantity: 0,
  },
  {
    id: 'UB-075',
    name: 'Hot Chocolate',
    price: '₹40',
    image: './css/images/food-items/Underbelly/hot chocolate.jpg',
    quantity: 0,
  },
  {
    id: 'UB-076',
    name: 'Black Coffee',
    price: '₹30',
    image: './css/images/food-items/Underbelly/black coffee.jpg',
    quantity: 0,
  },
  {
    id: 'UB-077',
    name: 'Vanilla Milkshake',
    price: '₹50',
    image: './css/images/food-items/Underbelly/vanilla milkshake.jpg',
    quantity: 0,
  },
  {
    id: 'UB-078',
    name: 'Chocolate Milkshake',
    price: '₹50',
    image: './css/images/food-items/Underbelly/chocolate milkshake.jpg',
    quantity: 0,
  },
  {
    id: 'UB-079',
    name: 'Butterscotch Milkshake',
    price: '₹50',
    image: './css/images/food-items/Underbelly/butterscotch milkshake.jpg',
    quantity: 0,
  },
  {
    id: 'UB-080',
    name: 'Oreo Milkshake',
    price: '₹60',
    image: './css/images/food-items/Underbelly/oreo milkshake.jpg',
    quantity: 0,
  },
  {
    id: 'UB-081',
    name: 'Kitkat Milkshake',
    price: '₹60',
    image: './css/images/food-items/Underbelly/kitkat milkshake.jpg',
    quantity: 0,
  },
  {
    id: 'UB-082',
    name: 'Cold Coffee',
    price: '₹50',
    image: './css/images/food-items/Underbelly/cold coffee.jpg',
    quantity: 0,
  },
  {
    id: 'UB-083',
    name: 'Orange Juice',
    price: '₹70',
    image: './css/images/food-items/Underbelly/orange juice.jpg',
    quantity: 0,
  },
  {
    id: 'UB-084',
    name: 'Sweet Lime Juice',
    price: '₹70',
    image: './css/images/food-items/Underbelly/sweet lime juice.jpg',
    quantity: 0,
  },
  {
    id: 'UB-085',
    name: 'Pineapple Juice',
    price: '₹70',
    image: './css/images/food-items/Underbelly/pineapple juice.jpg',
    quantity: 0,
  },
  {
    id: 'UB-086',
    name: 'Lime Mint Cooler',
    price: '₹42',
    image: './css/images/food-items/Underbelly/lime mint cooler.jpg',
    quantity: 0,
  },
  {
    id: 'UB-087',
    name: 'Choco Truffle Pastry',
    price: '₹80',
    image: './css/images/food-items/Underbelly/choco truffle pastry.jpg',
    quantity: 0,
  },
  {
    id: 'UB-088',
    name: 'Choco Doughnut',
    price: '₹42',
    image: './css/images/food-items/Underbelly/choco doughnut.jpg',
    quantity: 0,
  },
  {
    id: 'UB-089',
    name: 'Choco Truffle Cake (500g)',
    price: '₹550',
    image: './css/images/food-items/Underbelly/choco truffle cake 500g.jpg',
    quantity: 0,
  },
  {
    id: 'UB-090',
    name: 'Kitkat Cake (500g)',
    price: '₹550',
    image: './css/images/food-items/Underbelly/kitkat cake 500g.jpg',
    quantity: 0,
  },
  {
    id: 'UB-091',
    name: 'Oreo Cake (500g)',
    price: '₹550',
    image: './css/images/food-items/Underbelly/oreo cake 500g.jpg',
    quantity: 0,
  },
  {
    id: 'UB-092',
    name: 'Chocolate Cake (500g)',
    price: '₹550',
    image: './css/images/food-items/Underbelly/chocolate cake 500g.jpg',
    quantity: 0,
  },
  {
    id: 'UB-093',
    name: 'Choco Truffle Cake (1kg)',
    price: '₹950',
    image: './css/images/food-items/Underbelly/choco truffle cake 1kg.jpg',
    quantity: 0,
  },
  {
    id: 'UB-094',
    name: 'Kitkat Cake (1kg)',
    price: '₹1000',
    image: './css/images/food-items/Underbelly/kitkat cake 1kg.jpg',
    quantity: 0,
  },
  {
    id: 'UB-095',
    name: 'Oreo Cake (1kg)',
    price: '₹1000',
    image: './css/images/food-items/Underbelly/oreo cake 1kg.jpg',
    quantity: 0,
  },
  {
    id: 'UB-096',
    name: 'Chocolate Cake (1kg)',
    price: '₹900',
    image: './css/images/food-items/Underbelly/chocolate cake 1kg.jpg',
    quantity: 0,
  },
];
